server:
  port: 9091

#datasource
datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mydata?userUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: root
  autoCommit: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ywh.base.common.dao

#RSA非对称秘匙存放文件url
rsa:
  publicKeyFile: D:\\mycode\\keyfile\\public_key
  privateKeyFile: D:\\mycode\\keyfile\\private_key
