server:
  port: 9090

#datasource
datasource:
  url: jdbc:mysql://localhost:3306/mydata?userUnicode=true&characterEncoding=utf8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver